# fly.toml app configuration file generated for vaultwarden-makkamy on 2025-05-16T08:41:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vaultwarden-makkamy'
primary_region = 'arn'

[build]
image = "vaultwarden/server:latest"

[env]
DOMAIN = "https://vault.vangenwood.com"
ADMIN_TOKEN = "$argon2id$v=19$m=65540,t=3,p=4$QojxR4kvVxAeT+pkUo6a0EInLpFAOhYFJ9JpR+uN/0Q$B6OcNd5AgWgzzV+m16Kof0W7hZXSGdL2zZk3cXu8KLs"
ROCKET_ADDRESS = "0.0.0.0"
ROCKET_PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_cert = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[mounts]]
source = "vaultwarden_data"
destination = "/data"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
